# Generated by Django 4.0.4 on 2022-05-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='name')),
                ('favorite', models.BooleanField(default=False, verbose_name='favorite')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.TextField(verbose_name='title')),
                ('complete', models.BooleanField(default=False, verbose_name='complete')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='SubTasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.TextField(verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('do_notify', models.BooleanField(default=False, verbose_name='do_notify')),
                ('notify_period', models.DateTimeField(null=True, verbose_name='notify_period')),
                ('priority', models.SmallIntegerField(verbose_name='priority')),
                ('todositem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.todoitem')),
            ],
        ),
    ]
